# Generated by Django 4.2.9 on 2024-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reusme',
            new_name='Resume',
        ),
    ]
